### ISSUE TITLE
[privategpt] torch and sentence-transformers not found

### ISSUE THREAD

**Issue by eisc0013** [3x3cut0r/docker#10]
**Issue:** When clicking Submit in the web ui after writing a prompt, an error is displayed referring to the below.  If I attach to the container and run the pip install command, prompts are successfully processed and results are returned.  

**Desired outcome:** It would be handy if the supposedly missing packages were present in the images or installed as part of the container creation. 

OpenSUSE Tumbleweed host installed 2024-05-01 x64 on ESXi
Docker version 26.1.0-ce, build c8af8ebe4a89

privategpt  | ImportError: ('Cannot import sentence-transformers or torch package,', 'please `pip install torch sentence-transformers`')

docker-compose.yaml...
```
services:
  # https://hub.docker.com/r/3x3cut0r/privategpt
  privategpt:
    image: 3x3cut0r/privategpt:latest
    container_name: privategpt
    restart: on-failure:5
    ports:
      - 8080:8080/tcp
    environment:
      EMBEDDING_INGEST_MODE: "pipeline"
      EMBEDDING_COUNT_WORKERS: "44"
      RAG_RERANK_ENABLED: "true"
      RAG_SIMILARITY_TOP_K: "10"
      RAG_RERANK_TOP_N: "8"
      #NODESTOR_DATABASE: "postgres"
      #VECTORSTORE_DATABASE: "postgres"
      HUGGINGFACE_TOKEN: "mytokenhere"
```
