### ISSUE TITLE
docker-compose.yml for Postgres DB

### ISSUE THREAD

**Issue by AlexPerkin** [3x3cut0r/docker#19]
Hi,
Please provide a sample docker-compose.yml file for privategpt project in case of using postgres as DB.
In my case:

`VECTORSTORE_DATABASE: postgres
NODESTORE_DATABASE: postgres

POSTGRES_HOST: privategpt 
 POSTGRES_PORT: 5432
 POSTGRES_DATABASE: postgres
 POSTGRES_USER: postgres
 POSTGRES_PASSWORD: admin
 POSTGRES_SCHEMA_NAME: private_gpt`

Error:

`privategpt  | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "privategpt" (172.18.0.3), port 5432 failed: Connection refused
privategpt  |   Is the server running on that host and accepting TCP/IP connections?
`

Thanks in advance

**Comment by 3x3cut0r** [comment]
```
version: '3.9'

services:
  privategpt:
    image: 3x3cut0r/privategpt:latest
    container_name: privategpt
    environment:
      VECTORSTORE_DATABASE: postgres
      NODESTORE_DATABASE: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_SCHEMA_NAME: private_gpt
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - privategpt

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - privategpt

volumes:
  postgres_data:
    name: postgres_data
    
networks:
  privategpt:
    name: privategpt
    driver: bridge

```
