### ISSUE TITLE
[llama-cpp-python] llama-2-7b-chat.Q4_0.gguf model not loaded on GPU

### ISSUE THREAD

**Issue by sharifAhmd** [3x3cut0r/docker#4]
In docker compose, I am using these envs, but it is not loading the model in GPU
```
environment:
        MODEL: "/model/llama-2-7b-chat.Q4_0.gguf"
        MAIN_GPU: 1
        N_GPU_LAYERS: 500
```
